//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWA_MAIN
{


    public partial class MedSearch
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new FWA_MAIN.main Master
        {
            get
            {
                return ((FWA_MAIN.main)(base.Master));
            }
        }
    }
}
